version: "3"

services:
  web:
    image: nginx
    depends_on:
      - app
    ports:
      - ${WEB_PORT:-8080}:80
    volumes:
      - ${APP_ROOT_PATH}:/var/www/html
      - ./web/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build: ./app
    depends_on:
      - db
    volumes:
      - ${APP_ROOT_PATH}:/var/www/html
      - ./app/php.ini:/usr/local/etc/php/php.ini

  db:
    image: postgres:12.2-alpine
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-docker}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-docker}
      POSTGRES_DB: ${DB_NAME:-docker}

volumes:
  pgdata:
